# Stubs for django.core.mail.backends.console (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.core.mail.backends.base import BaseEmailBackend

class EmailBackend(BaseEmailBackend):
    stream = ...  # type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def write_message(self, message): ...
    def send_messages(self, email_messages): ...
