# Stubs for django.core.mail.backends.filebased (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.core.mail.backends.console import EmailBackend as ConsoleEmailBackend

class EmailBackend(ConsoleEmailBackend):
    file_path = ...  # type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def write_message(self, message): ...
    stream = ...  # type: Any
    def open(self): ...
    def close(self): ...
