# Stubs for django.core.mail.backends.smtp (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.core.mail.backends.base import BaseEmailBackend

class EmailBackend(BaseEmailBackend):
    host = ...  # type: Any
    port = ...  # type: Any
    username = ...  # type: Any
    password = ...  # type: Any
    use_tls = ...  # type: Any
    use_ssl = ...  # type: Any
    timeout = ...  # type: Any
    ssl_keyfile = ...  # type: Any
    ssl_certfile = ...  # type: Any
    connection = ...  # type: Any
    def __init__(self, host: Optional[Any] = ..., port: Optional[Any] = ..., username: Optional[Any] = ..., password: Optional[Any] = ..., use_tls: Optional[Any] = ..., fail_silently: bool = ..., use_ssl: Optional[Any] = ..., timeout: Optional[Any] = ..., ssl_keyfile: Optional[Any] = ..., ssl_certfile: Optional[Any] = ..., **kwargs) -> None: ...
    def open(self): ...
    def close(self): ...
    def send_messages(self, email_messages): ...
