# Stubs for django.contrib.gis.geos.prototypes.geom (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from ctypes import c_char_p
from django.contrib.gis.geos.libgeos import GEOSFuncFactory

c_uchar_p = ...  # type: Any

class geos_char_p(c_char_p): ...

class BinConstructor(GEOSFuncFactory):
    argtypes = ...  # type: Any
    restype = ...  # type: Any
    errcheck = ...  # type: Any

class BinOutput(GEOSFuncFactory):
    argtypes = ...  # type: Any
    restype = ...  # type: Any
    errcheck = ...  # type: Any

class GeomOutput(GEOSFuncFactory):
    restype = ...  # type: Any
    errcheck = ...  # type: Any
    argtypes = ...  # type: Any
    def get_func(self, argtypes): ...

class IntFromGeom(GEOSFuncFactory):
    argtypes = ...  # type: Any
    restype = ...  # type: Any
    errcheck = ...  # type: Any
    def get_func(self, zero: bool = ...): ...

class StringFromGeom(GEOSFuncFactory):
    argtypes = ...  # type: Any
    restype = ...  # type: Any
    errcheck = ...  # type: Any

from_hex = ...  # type: Any
from_wkb = ...  # type: Any
from_wkt = ...  # type: Any
to_hex = ...  # type: Any
to_wkb = ...  # type: Any
to_wkt = ...  # type: Any
geos_normalize = ...  # type: Any
geos_type = ...  # type: Any
geos_typeid = ...  # type: Any
get_dims = ...  # type: Any
get_num_coords = ...  # type: Any
get_num_geoms = ...  # type: Any
create_point = ...  # type: Any
create_linestring = ...  # type: Any
create_linearring = ...  # type: Any
create_polygon = ...  # type: Any
create_collection = ...  # type: Any
get_extring = ...  # type: Any
get_intring = ...  # type: Any
get_nrings = ...  # type: Any
get_geomn = ...  # type: Any
geom_clone = ...  # type: Any
destroy_geom = ...  # type: Any
geos_get_srid = ...  # type: Any
geos_set_srid = ...  # type: Any
