# Stubs for django.contrib.gis.geos.prototypes.predicates (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.contrib.gis.geos.libgeos import GEOSFuncFactory

class UnaryPredicate(GEOSFuncFactory):
    argtypes = ...  # type: Any
    restype = ...  # type: Any
    errcheck = ...  # type: Any

class BinaryPredicate(UnaryPredicate):
    argtypes = ...  # type: Any

geos_hasz = ...  # type: Any
geos_isempty = ...  # type: Any
geos_isring = ...  # type: Any
geos_issimple = ...  # type: Any
geos_isvalid = ...  # type: Any
geos_contains = ...  # type: Any
geos_crosses = ...  # type: Any
geos_disjoint = ...  # type: Any
geos_equals = ...  # type: Any
geos_equalsexact = ...  # type: Any
geos_intersects = ...  # type: Any
geos_overlaps = ...  # type: Any
geos_relatepattern = ...  # type: Any
geos_touches = ...  # type: Any
geos_within = ...  # type: Any
