# Stubs for django.contrib.gis.geos.prototypes.prepared (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.contrib.gis.geos.libgeos import GEOSFuncFactory

geos_prepare = ...  # type: Any
prepared_destroy = ...  # type: Any

class PreparedPredicate(GEOSFuncFactory):
    argtypes = ...  # type: Any
    restype = ...  # type: Any
    errcheck = ...  # type: Any

prepared_contains = ...  # type: Any
prepared_contains_properly = ...  # type: Any
prepared_covers = ...  # type: Any
prepared_intersects = ...  # type: Any
prepared_crosses = ...  # type: Any
prepared_disjoint = ...  # type: Any
prepared_overlaps = ...  # type: Any
prepared_touches = ...  # type: Any
prepared_within = ...  # type: Any
