# Stubs for django.contrib.gis.geos.prototypes.topology (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.contrib.gis.geos.libgeos import GEOSFuncFactory

class Topology(GEOSFuncFactory):
    argtypes = ...  # type: Any
    restype = ...  # type: Any
    errcheck = ...  # type: Any

geos_boundary = ...  # type: Any
geos_buffer = ...  # type: Any
geos_centroid = ...  # type: Any
geos_convexhull = ...  # type: Any
geos_difference = ...  # type: Any
geos_envelope = ...  # type: Any
geos_intersection = ...  # type: Any
geos_linemerge = ...  # type: Any
geos_pointonsurface = ...  # type: Any
geos_preservesimplify = ...  # type: Any
geos_simplify = ...  # type: Any
geos_symdifference = ...  # type: Any
geos_union = ...  # type: Any
geos_cascaded_union = ...  # type: Any
geos_relate = ...  # type: Any
geos_project = ...  # type: Any
geos_interpolate = ...  # type: Any
geos_project_normalized = ...  # type: Any
geos_interpolate_normalized = ...  # type: Any
