# Stubs for django.db.migrations.operations (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .fields import AddField as AddField, AlterField as AlterField, RemoveField as RemoveField, RenameField as RenameField
from .models import AlterIndexTogether as AlterIndexTogether, AlterModelManagers as AlterModelManagers, AlterModelOptions as AlterModelOptions, AlterModelTable as AlterModelTable, AlterOrderWithRespectTo as AlterOrderWithRespectTo, AlterUniqueTogether as AlterUniqueTogether, CreateModel as CreateModel, DeleteModel as DeleteModel, RenameModel as RenameModel
from .special import RunPython as RunPython, RunSQL as RunSQL, SeparateDatabaseAndState as SeparateDatabaseAndState
