# Stubs for django.contrib.admin.templatetags.admin_modify (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

register = ...  # type: Any

def prepopulated_fields_js(context): ...
def submit_row(context): ...
def cell_count(inline_admin_form): ...
