# Stubs for django.contrib.admin.templatetags.admin_urls (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

register = ...  # type: Any

def admin_urlname(value, arg): ...
def admin_urlquote(value): ...
def add_preserved_filters(context, url, popup: bool = ..., to_field: Optional[Any] = ...): ...
