# Stubs for django.contrib.admin.templatetags.admin_static (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

register = ...  # type: Any

def static(path): ...
