# Stubs for django.contrib.gis.management.commands.inspectdb (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.core.management.commands.inspectdb import Command as InspectDBCommand

class Command(InspectDBCommand):
    db_module = ...  # type: str
    def get_field_type(self, connection, table_name, row): ...
