# Stubs for django.conf.urls (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

handler400 = ...  # type: str
handler403 = ...  # type: str
handler404 = ...  # type: str
handler500 = ...  # type: str

def include(arg, namespace: Optional[Any] = ..., app_name: Optional[Any] = ...): ...
def patterns(prefix, *args): ...
def url(regex, view, kwargs: Optional[Any] = ..., name: Optional[Any] = ..., prefix: str = ...): ...
