# Stubs for django.conf.urls.i18n (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def i18n_patterns(prefix, *args): ...

urlpatterns = ...  # type: Any
