# Stubs for django.conf.urls.static (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def static(prefix, view: Any = ..., **kwargs): ...
