# Stubs for django.contrib.gis.db.backends.utils (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class SpatialOperator:
    sql_template = ...  # type: Any
    op = ...  # type: Any
    func = ...  # type: Any
    def __init__(self, op: Optional[Any] = ..., func: Optional[Any] = ...) -> None: ...
    @property
    def default_template(self): ...
    def as_sql(self, connection, lookup, template_params, sql_params): ...
