# Stubs for django.core.management.commands.compilemessages (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.core.management.base import BaseCommand

def has_bom(fn): ...
def is_writable(path): ...

class Command(BaseCommand):
    help = ...  # type: str
    requires_system_checks = ...  # type: bool
    leave_locale_alone = ...  # type: bool
    program = ...  # type: str
    program_options = ...  # type: Any
    def add_arguments(self, parser): ...
    verbosity = ...  # type: Any
    def handle(self, **options): ...
    def compile_messages(self, locations): ...
