# Stubs for django.core.management.commands.createcachetable (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.core.management.base import BaseCommand

class Command(BaseCommand):
    help = ...  # type: str
    requires_system_checks = ...  # type: bool
    def add_arguments(self, parser): ...
    verbosity = ...  # type: Any
    def handle(self, *tablenames, **options): ...
    def create_table(self, database, tablename, dry_run): ...
