# Stubs for django.core.management.commands.diffsettings (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.core.management.base import BaseCommand

def module_to_dict(module, omittable: Any = ...): ...

class Command(BaseCommand):
    help = ...  # type: str
    requires_system_checks = ...  # type: bool
    def add_arguments(self, parser): ...
    def handle(self, **options): ...
