# Stubs for django.core.management.commands.loaddata (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import zipfile
from django.core.management.base import BaseCommand

has_bz2 = ...  # type: bool

class Command(BaseCommand):
    help = ...  # type: str
    missing_args_message = ...  # type: str
    def add_arguments(self, parser): ...
    ignore = ...  # type: Any
    using = ...  # type: Any
    app_label = ...  # type: Any
    hide_empty = ...  # type: Any
    verbosity = ...  # type: Any
    def handle(self, *fixture_labels, **options): ...
    fixture_count = ...  # type: int
    loaded_object_count = ...  # type: int
    fixture_object_count = ...  # type: int
    models = ...  # type: Any
    serialization_formats = ...  # type: Any
    compression_formats = ...  # type: Any
    def loaddata(self, fixture_labels): ...
    def load_label(self, fixture_label): ...
    def find_fixtures(self, fixture_label): ...
    def fixture_dirs(self): ...
    def parse_name(self, fixture_name): ...

class SingleZipReader(zipfile.ZipFile):
    def __init__(self, *args, **kwargs) -> None: ...
    def read(self): ...

def humanize(dirname): ...
