# Stubs for django.contrib.postgres.lookups (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.models import Lookup, Transform

class PostgresSimpleLookup(Lookup):
    def as_sql(self, qn, connection): ...

class DataContains(PostgresSimpleLookup):
    lookup_name = ...  # type: str
    operator = ...  # type: str

class ContainedBy(PostgresSimpleLookup):
    lookup_name = ...  # type: str
    operator = ...  # type: str

class Overlap(PostgresSimpleLookup):
    lookup_name = ...  # type: str
    operator = ...  # type: str

class HasKey(PostgresSimpleLookup):
    lookup_name = ...  # type: str
    operator = ...  # type: str

class HasKeys(PostgresSimpleLookup):
    lookup_name = ...  # type: str
    operator = ...  # type: str

class HasAnyKeys(PostgresSimpleLookup):
    lookup_name = ...  # type: str
    operator = ...  # type: str

class Unaccent(Transform):
    bilateral = ...  # type: bool
    lookup_name = ...  # type: str
    function = ...  # type: str
