# Stubs for django.contrib.postgres.validators (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.core.validators import MaxLengthValidator, MaxValueValidator, MinLengthValidator, MinValueValidator
from django.utils.translation import ugettext_lazy as _

class ArrayMaxLengthValidator(MaxLengthValidator):
    message = ...  # type: Any

class ArrayMinLengthValidator(MinLengthValidator):
    message = ...  # type: Any

class KeysValidator:
    messages = ...  # type: Any
    strict = ...  # type: bool
    keys = ...  # type: Any
    def __init__(self, keys, strict: bool = ..., messages: Optional[Any] = ...) -> None: ...
    def __call__(self, value): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

class RangeMaxValueValidator(MaxValueValidator):
    compare = ...  # type: Any
    message = ...  # type: Any

class RangeMinValueValidator(MinValueValidator):
    compare = ...  # type: Any
    message = ...  # type: Any
