# Stubs for django.contrib.sitemaps.management.commands.ping_google (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.core.management.base import BaseCommand

class Command(BaseCommand):
    help = ...  # type: str
    def add_arguments(self, parser): ...
    def handle(self, *args, **options): ...
