# Stubs for django.contrib.auth.migrations.0006_require_contenttypes_0002 (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import migrations

class Migration(migrations.Migration):
    dependencies = ...  # type: Any
    operations = ...  # type: Any
