# Stubs for django.contrib.sites.apps (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.apps import AppConfig
from django.utils.translation import ugettext_lazy as _
from .management import create_default_site as create_default_site

class SitesConfig(AppConfig):
    name = ...  # type: str
    verbose_name = ...  # type: Any
    def ready(self): ...
