# Stubs for django.contrib.sites.middleware (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .shortcuts import get_current_site as get_current_site

class CurrentSiteMiddleware:
    def process_request(self, request): ...
