# Stubs for django.contrib.sites.requests (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class RequestSite:
    domain = ...  # type: Any
    def __init__(self, request) -> None: ...
    def save(self, force_insert: bool = ..., force_update: bool = ...): ...
    def delete(self): ...
