# Stubs for django.utils.dates (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.utils.translation import ugettext_lazy as _

WEEKDAYS = ...  # type: Any
WEEKDAYS_ABBR = ...  # type: Any
WEEKDAYS_REV = ...  # type: Any
MONTHS = ...  # type: Any
MONTHS_3 = ...  # type: Any
MONTHS_3_REV = ...  # type: Any
MONTHS_AP = ...  # type: Any
MONTHS_ALT = ...  # type: Any
