# Stubs for django.utils.dateparse (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

date_re = ...  # type: Any
time_re = ...  # type: Any
datetime_re = ...  # type: Any
standard_duration_re = ...  # type: Any
iso8601_duration_re = ...  # type: Any

def parse_date(value): ...
def parse_time(value): ...
def parse_datetime(value): ...
def parse_duration(value): ...
