# Stubs for django.utils.ipv6 (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.utils.translation import ugettext_lazy as _

def clean_ipv6_address(ip_str, unpack_ipv4: bool = ..., error_message: Any = ...): ...
def is_valid_ipv6_address(ip_str): ...
