# Stubs for django.utils.jslex (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class Tok:
    num = ...  # type: int
    id = ...  # type: Any
    name = ...  # type: Any
    regex = ...  # type: Any
    next = ...  # type: Any
    def __init__(self, name, regex, next: Optional[Any] = ...) -> None: ...

def literals(choices, prefix: str = ..., suffix: str = ...): ...

class Lexer:
    regexes = ...  # type: Any
    toks = ...  # type: Any
    state = ...  # type: Any
    def __init__(self, states, first) -> None: ...
    def lex(self, text): ...

class JsLexer(Lexer):
    both_before = ...  # type: Any
    both_after = ...  # type: Any
    states = ...  # type: Any
    def __init__(self) -> None: ...

def prepare_js_for_gettext(js): ...
