# Stubs for django.utils.lorem_ipsum (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

COMMON_P = ...  # type: str
WORDS = ...  # type: Any
COMMON_WORDS = ...  # type: Any

def sentence(): ...
def paragraph(): ...
def paragraphs(count, common: bool = ...): ...
def words(count, common: bool = ...): ...
