# Stubs for django.utils.termcolors (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

color_names = ...  # type: Any
foreground = ...  # type: Any
background = ...  # type: Any
RESET = ...  # type: str
opt_dict = ...  # type: Any

def colorize(text: str = ..., opts: Any = ..., **kwargs): ...
def make_style(opts: Any = ..., **kwargs): ...

NOCOLOR_PALETTE = ...  # type: str
DARK_PALETTE = ...  # type: str
LIGHT_PALETTE = ...  # type: str
PALETTES = ...  # type: Any
DEFAULT_PALETTE = ...  # type: Any

def parse_color_setting(config_string): ...
