# Stubs for django.utils.timesince (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

TIMESINCE_CHUNKS = ...  # type: Any

def timesince(d, now: Optional[Any] = ..., reversed: bool = ...): ...
def timeuntil(d, now: Optional[Any] = ...): ...
