# Stubs for django.contrib.sessions.management.commands.clearsessions (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.core.management.base import BaseCommand

class Command(BaseCommand):
    help = ...  # type: str
    def handle(self, **options): ...
