# Stubs for django.contrib.admin.actions (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.translation import ugettext as _

def delete_selected(modeladmin, request, queryset): ...
