# Stubs for django.template (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from .engine import Engine as Engine
from .base import Context as Context, RequestContext as RequestContext, Template as Template

engines = ...  # type: Any
