# Stubs for django.core.files.temp (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class TemporaryFile(FileProxyMixin):
    name = ...  # type: Any
    file = ...  # type: Any
    close_called = ...  # type: bool
    def __init__(self, mode: str = ..., bufsize: int = ..., suffix: str = ..., prefix: str = ..., dir: Optional[Any] = ...) -> None: ...
    unlink = ...  # type: Any
    def close(self): ...
    @property
    def closed(self): ...
    def __del__(self): ...
    def __enter__(self): ...
    def __exit__(self, exc, value, tb): ...

NamedTemporaryFile = ...  # type: Any
gettempdir = ...  # type: Any
