# Stubs for django.core.signals (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

request_started = ...  # type: Any
request_finished = ...  # type: Any
got_request_exception = ...  # type: Any
setting_changed = ...  # type: Any
