# Stubs for django.contrib.gis.gdal.raster.const (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

GDAL_PIXEL_TYPES = ...  # type: Any
GDAL_INTEGER_TYPES = ...  # type: Any
GDAL_TO_CTYPES = ...  # type: Any
GDAL_RESAMPLE_ALGORITHMS = ...  # type: Any
