# Stubs for django.contrib.webdesign.templatetags.webdesign (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

register = ...  # type: Any
