# Stubs for django.dispatch.dispatcher (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from .weakref_backports import WeakMethod as WeakMethod

NONE_ID = ...  # type: Any
NO_RECEIVERS = ...  # type: Any

class Signal:
    receivers = ...  # type: Any
    providing_args = ...  # type: Any
    lock = ...  # type: Any
    use_caching = ...  # type: Any
    sender_receivers_cache = ...  # type: Any
    def __init__(self, providing_args: Optional[Any] = ..., use_caching: bool = ...) -> None: ...
    def connect(self, receiver, sender: Optional[Any] = ..., weak: bool = ..., dispatch_uid: Optional[Any] = ...): ...
    def disconnect(self, receiver: Optional[Any] = ..., sender: Optional[Any] = ..., weak: Optional[Any] = ..., dispatch_uid: Optional[Any] = ...): ...
    def has_listeners(self, sender: Optional[Any] = ...): ...
    def send(self, sender, **named): ...
    def send_robust(self, sender, **named): ...

def receiver(signal, **kwargs): ...
