# Stubs for django.conf.locale.gd.formats (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

DATE_FORMAT = ...  # type: str
TIME_FORMAT = ...  # type: str
DATETIME_FORMAT = ...  # type: str
MONTH_DAY_FORMAT = ...  # type: str
SHORT_DATE_FORMAT = ...  # type: str
SHORT_DATETIME_FORMAT = ...  # type: str
FIRST_DAY_OF_WEEK = ...  # type: int
DECIMAL_SEPARATOR = ...  # type: str
THOUSAND_SEPARATOR = ...  # type: str
