# Stubs for django.db.backends.postgresql.features (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.db.backends.base.features import BaseDatabaseFeatures

class DatabaseFeatures(BaseDatabaseFeatures):
    allows_group_by_selected_pks = ...  # type: bool
    can_return_id_from_insert = ...  # type: bool
    has_real_datatype = ...  # type: bool
    has_native_uuid_field = ...  # type: bool
    has_native_duration_field = ...  # type: bool
    driver_supports_timedelta_args = ...  # type: bool
    can_defer_constraint_checks = ...  # type: bool
    has_select_for_update = ...  # type: bool
    has_select_for_update_nowait = ...  # type: bool
    has_bulk_insert = ...  # type: bool
    uses_savepoints = ...  # type: bool
    can_release_savepoints = ...  # type: bool
    supports_tablespaces = ...  # type: bool
    supports_transactions = ...  # type: bool
    can_introspect_autofield = ...  # type: bool
    can_introspect_ip_address_field = ...  # type: bool
    can_introspect_small_integer_field = ...  # type: bool
    can_distinct_on_fields = ...  # type: bool
    can_rollback_ddl = ...  # type: bool
    supports_combined_alters = ...  # type: bool
    nulls_order_largest = ...  # type: bool
    closed_cursor_error_class = ...  # type: Any
    has_case_insensitive_like = ...  # type: bool
    requires_sqlparse_for_splitting = ...  # type: bool
    greatest_least_ignores_nulls = ...  # type: bool
    can_clone_databases = ...  # type: bool
