# Stubs for django.db.backends.postgresql.version (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

VERSION_RE = ...  # type: Any

def get_version(connection): ...
