# Stubs for django.db.backends.base.client (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class BaseDatabaseClient:
    executable_name = ...  # type: Any
    connection = ...  # type: Any
    def __init__(self, connection) -> None: ...
    def runshell(self): ...
