# Stubs for django.db.backends.base.validation (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class BaseDatabaseValidation:
    connection = ...  # type: Any
    def __init__(self, connection) -> None: ...
    def check_field(self, field, **kwargs): ...
