# Stubs for django.contrib.auth.signals (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

user_logged_in = ...  # type: Any
user_login_failed = ...  # type: Any
user_logged_out = ...  # type: Any
