# Stubs for django.contrib.auth.tokens (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class PasswordResetTokenGenerator:
    key_salt = ...  # type: str
    def make_token(self, user): ...
    def check_token(self, user, token): ...

default_token_generator = ...  # type: Any
