# Stubs for django.contrib.gis.maps.google (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.gis.maps.google.gmap import GoogleMap as GoogleMap, GoogleMapSet as GoogleMapSet
from django.contrib.gis.maps.google.overlays import GEvent as GEvent, GIcon as GIcon, GMarker as GMarker, GPolygon as GPolygon, GPolyline as GPolyline
from django.contrib.gis.maps.google.zoom import GoogleZoom as GoogleZoom
