# Stubs for django.contrib.gis.maps.google.gmap (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class GoogleMapException(Exception): ...

GOOGLE_MAPS_URL = ...  # type: str

class GoogleMap:
    onunload = ...  # type: Any
    vml_css = ...  # type: Any
    xmlns = ...  # type: Any
    key = ...  # type: Any
    version = ...  # type: Any
    api_url = ...  # type: Any
    dom_id = ...  # type: Any
    extra_context = ...  # type: Any
    js_module = ...  # type: Any
    template = ...  # type: Any
    kml_urls = ...  # type: Any
    calc_zoom = ...  # type: bool
    zoom = ...  # type: Any
    center = ...  # type: Any
    def __init__(self, key: Optional[Any] = ..., api_url: Optional[Any] = ..., version: Optional[Any] = ..., center: Optional[Any] = ..., zoom: Optional[Any] = ..., dom_id: str = ..., kml_urls: Any = ..., polylines: Optional[Any] = ..., polygons: Optional[Any] = ..., markers: Optional[Any] = ..., template: str = ..., js_module: str = ..., extra_context: Any = ...) -> None: ...
    def render(self): ...
    @property
    def body(self): ...
    @property
    def onload(self): ...
    @property
    def api_script(self): ...
    @property
    def js(self): ...
    @property
    def scripts(self): ...
    @property
    def style(self): ...
    @property
    def xhtml(self): ...
    @property
    def icons(self): ...

class GoogleMapSet(GoogleMap):
    map_template = ...  # type: Any
    template = ...  # type: Any
    maps = ...  # type: Any
    dom_ids = ...  # type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def load_map_js(self): ...
    def render(self): ...
    @property
    def onload(self): ...
    @property
    def icons(self): ...
