# Stubs for django.db.migrations (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .migration import Migration as Migration, swappable_dependency as swappable_dependency
from .operations import *
