# Stubs for django.db.migrations.utils (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

COMPILED_REGEX_TYPE = ...  # type: Any

class RegexObject:
    pattern = ...  # type: Any
    flags = ...  # type: Any
    def __init__(self, obj) -> None: ...
    def __eq__(self, other): ...
