# Stubs for django.contrib.contenttypes.management (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def update_contenttypes(app_config, verbosity: int = ..., interactive: bool = ..., using: Any = ..., **kwargs): ...
