# Stubs for django.db.models.fields.proxy (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import fields

class OrderWrt(fields.IntegerField):
    def __init__(self, *args, **kwargs) -> None: ...
    def deconstruct(self): ...
