# Stubs for django.templatetags.future (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

register = ...  # type: Any

def cycle(parser, token): ...
def firstof(parser, token): ...
