# Stubs for django.middleware.cache (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class UpdateCacheMiddleware:
    cache_timeout = ...  # type: Any
    key_prefix = ...  # type: Any
    cache_alias = ...  # type: Any
    cache = ...  # type: Any
    def __init__(self) -> None: ...
    def process_response(self, request, response): ...

class FetchFromCacheMiddleware:
    key_prefix = ...  # type: Any
    cache_alias = ...  # type: Any
    cache = ...  # type: Any
    def __init__(self) -> None: ...
    def process_request(self, request): ...

class CacheMiddleware(UpdateCacheMiddleware, FetchFromCacheMiddleware):
    key_prefix = ...  # type: Any
    cache_alias = ...  # type: Any
    cache_timeout = ...  # type: Any
    cache = ...  # type: Any
    def __init__(self, cache_timeout: Optional[Any] = ..., **kwargs) -> None: ...
