# Stubs for django.middleware.clickjacking (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class XFrameOptionsMiddleware:
    def process_response(self, request, response): ...
    def get_xframe_options_value(self, request, response): ...
