# Stubs for django.middleware.csrf (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

logger = ...  # type: Any
REASON_NO_REFERER = ...  # type: str
REASON_BAD_REFERER = ...  # type: str
REASON_NO_CSRF_COOKIE = ...  # type: str
REASON_BAD_TOKEN = ...  # type: str
REASON_MALFORMED_REFERER = ...  # type: str
REASON_INSECURE_REFERER = ...  # type: str
CSRF_KEY_LENGTH = ...  # type: int

def get_token(request): ...
def rotate_token(request): ...

class CsrfViewMiddleware:
    def process_view(self, request, callback, callback_args, callback_kwargs): ...
    def process_response(self, request, response): ...
