# Stubs for django.middleware.gzip (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

re_accepts_gzip = ...  # type: Any

class GZipMiddleware:
    def process_response(self, request, response): ...
