# Stubs for django.middleware.http (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class ConditionalGetMiddleware:
    def process_response(self, request, response): ...
