# Stubs for django.middleware.locale (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class LocaleMiddleware:
    response_redirect_class = ...  # type: Any
    def process_request(self, request): ...
    def process_response(self, request, response): ...
    def is_language_prefix_patterns_used(self): ...
