# Stubs for django.contrib.sessions.middleware (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class SessionMiddleware:
    SessionStore = ...  # type: Any
    def __init__(self) -> None: ...
    def process_request(self, request): ...
    def process_response(self, request, response): ...
