# Stubs for django.contrib.sessions.serializers (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.core.signing import JSONSerializer as BaseJSONSerializer
from django.utils.six.moves import cPickle as pickle

class PickleSerializer:
    def dumps(self, obj): ...
    def loads(self, data): ...

JSONSerializer = ...  # type: Any
