# Stubs for django.conf.locale.sq.formats (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

DATE_FORMAT = ...  # type: str
TIME_FORMAT = ...  # type: str
YEAR_MONTH_FORMAT = ...  # type: str
MONTH_DAY_FORMAT = ...  # type: str
SHORT_DATE_FORMAT = ...  # type: str
DECIMAL_SEPARATOR = ...  # type: str
THOUSAND_SEPARATOR = ...  # type: str
