# Stubs for django.core.management.utils (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from .base import CommandError as CommandError

def popen_wrapper(args, os_err_exc_type: Any = ..., universal_newlines: bool = ...): ...
def handle_extensions(extensions): ...
def find_command(cmd, path: Optional[Any] = ..., pathext: Optional[Any] = ...): ...
