# Stubs for django.contrib.gis.gdal.error (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class GDALException(Exception): ...

OGRException = ...  # type: Any

class SRSException(Exception): ...

class OGRIndexError(GDALException, KeyError):
    silent_variable_failure = ...  # type: bool

OGRERR_DICT = ...  # type: Any
CPLERR_DICT = ...  # type: Any
ERR_NONE = ...  # type: int

def check_err(code, cpl: bool = ...): ...
