# Stubs for django.db.models.sql.constants (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

QUERY_TERMS = ...  # type: Any
GET_ITERATOR_CHUNK_SIZE = ...  # type: int
MULTI = ...  # type: str
SINGLE = ...  # type: str
CURSOR = ...  # type: str
NO_RESULTS = ...  # type: str
ORDER_PATTERN = ...  # type: Any
ORDER_DIR = ...  # type: Any
INNER = ...  # type: str
LOUTER = ...  # type: str
