# Stubs for django.apps.config (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

MODELS_MODULE_NAME = ...  # type: str

class AppConfig:
    name = ...  # type: Any
    module = ...  # type: Any
    label = ...  # type: Any
    verbose_name = ...  # type: Any
    path = ...  # type: Any
    models_module = ...  # type: Any
    models = ...  # type: Any
    def __init__(self, app_name, app_module) -> None: ...
    @classmethod
    def create(cls, entry): ...
    def check_models_ready(self): ...
    def get_model(self, model_name): ...
    def get_models(self, include_auto_created: bool = ..., include_deferred: bool = ..., include_swapped: bool = ...): ...
    def import_models(self, all_models): ...
    def ready(self): ...
