# Stubs for django.conf.locale.es.formats (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

DATE_FORMAT = ...  # type: str
TIME_FORMAT = ...  # type: str
DATETIME_FORMAT = ...  # type: str
YEAR_MONTH_FORMAT = ...  # type: str
MONTH_DAY_FORMAT = ...  # type: str
SHORT_DATE_FORMAT = ...  # type: str
SHORT_DATETIME_FORMAT = ...  # type: str
FIRST_DAY_OF_WEEK = ...  # type: int
DATE_INPUT_FORMATS = ...  # type: Any
DATETIME_INPUT_FORMATS = ...  # type: Any
DECIMAL_SEPARATOR = ...  # type: str
THOUSAND_SEPARATOR = ...  # type: str
NUMBER_GROUPING = ...  # type: int
