# Stubs for django.template.backends.dummy (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
import string
from .base import BaseEngine as BaseEngine
from .utils import csrf_input_lazy as csrf_input_lazy, csrf_token_lazy as csrf_token_lazy

class TemplateStrings(BaseEngine):
    app_dirname = ...  # type: str
    def __init__(self, params) -> None: ...
    def from_string(self, template_code): ...
    def get_template(self, template_name): ...

class Template(string.Template):
    def render(self, context: Optional[Any] = ..., request: Optional[Any] = ...): ...
