# Stubs for django.template.backends.jinja2 (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from .base import BaseEngine as BaseEngine
from .utils import csrf_input_lazy as csrf_input_lazy, csrf_token_lazy as csrf_token_lazy

class Jinja2(BaseEngine):
    app_dirname = ...  # type: str
    env = ...  # type: Any
    def __init__(self, params) -> None: ...
    def from_string(self, template_code): ...
    def get_template(self, template_name): ...

class Template:
    template = ...  # type: Any
    origin = ...  # type: Any
    def __init__(self, template) -> None: ...
    def render(self, context: Optional[Any] = ..., request: Optional[Any] = ...): ...

class Origin:
    name = ...  # type: Any
    template_name = ...  # type: Any
    def __init__(self, name, template_name) -> None: ...

def get_exception_info(exception): ...
