# Stubs for django.template.backends.utils (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def csrf_input(request): ...

csrf_input_lazy = ...  # type: Any
csrf_token_lazy = ...  # type: Any
