# Stubs for django.db.models.signals (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.dispatch import Signal

class_prepared = ...  # type: Any

class ModelSignal(Signal):
    unresolved_references = ...  # type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def connect(self, receiver, sender: Optional[Any] = ..., weak: bool = ..., dispatch_uid: Optional[Any] = ...): ...

pre_init = ...  # type: Any
post_init = ...  # type: Any
pre_save = ...  # type: Any
post_save = ...  # type: Any
pre_delete = ...  # type: Any
post_delete = ...  # type: Any
m2m_changed = ...  # type: Any
pre_migrate = ...  # type: Any
post_migrate = ...  # type: Any
