# Stubs for django.core.serializers.json (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import json
from django.core.serializers.python import Deserializer as PythonDeserializer, Serializer as PythonSerializer

class Serializer(PythonSerializer):
    internal_use_only = ...  # type: bool
    def start_serialization(self): ...
    def end_serialization(self): ...
    def end_object(self, obj): ...
    def getvalue(self): ...

def Deserializer(stream_or_string, **options): ...

class DjangoJSONEncoder(json.JSONEncoder):
    def default(self, o): ...

DateTimeAwareJSONEncoder = ...  # type: Any
