# Stubs for django.contrib.gis.db.backends.base.adapter (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class WKTAdapter:
    wkt = ...  # type: Any
    srid = ...  # type: Any
    def __init__(self, geom) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
