# Stubs for django.views.csrf (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.utils.translation import ugettext as _

CSRF_FAILURE_TEMPLATE = ...  # type: str

def csrf_failure(request, reason: str = ...): ...
