# Stubs for django.views.static (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.utils.translation import ugettext as _

def serve(request, path, document_root: Optional[Any] = ..., show_indexes: bool = ...): ...

DEFAULT_DIRECTORY_INDEX_TEMPLATE = ...  # type: str
template_translatable = ...  # type: Any

def directory_index(path, fullpath): ...
def was_modified_since(header: Optional[Any] = ..., mtime: int = ..., size: int = ...): ...
