# Stubs for django.contrib.gis.geos (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .collections import GeometryCollection as GeometryCollection, MultiLineString as MultiLineString, MultiPoint as MultiPoint, MultiPolygon as MultiPolygon
from .error import GEOSException as GEOSException
from .factory import fromfile as fromfile, fromstr as fromstr
from .geometry import GEOSGeometry as GEOSGeometry, hex_regex as hex_regex, wkt_regex as wkt_regex
from .io import WKBReader as WKBReader, WKBWriter as WKBWriter, WKTReader as WKTReader, WKTWriter as WKTWriter
from .libgeos import geos_version as geos_version, geos_version_info as geos_version_info
from .linestring import LinearRing as LinearRing, LineString as LineString
from .point import Point as Point
from .polygon import Polygon as Polygon

HAS_GEOS = ...  # type: bool
