# Stubs for django.contrib.gis.geos.base (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class GEOSBase:
    ptr_type = ...  # type: Any
    ptr = ...  # type: Any
