# Stubs for django.contrib.gis.geos.collections (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.contrib.gis.geos import prototypes as capi
from django.contrib.gis.geos.geometry import GEOSGeometry, ProjectInterpolateMixin

class GeometryCollection(GEOSGeometry):
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self): ...
    def __len__(self): ...
    @property
    def json(self): ...
    geojson = ...  # type: Any
    @property
    def kml(self): ...
    @property
    def tuple(self): ...
    coords = ...  # type: Any

class MultiPoint(GeometryCollection): ...

class MultiLineString(ProjectInterpolateMixin, GeometryCollection):
    @property
    def merged(self): ...

class MultiPolygon(GeometryCollection):
    @property
    def cascaded_union(self): ...
