# Stubs for django.db.backends.mysql.creation (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.base.creation import BaseDatabaseCreation
from .client import DatabaseClient as DatabaseClient

class DatabaseCreation(BaseDatabaseCreation):
    def sql_table_creation_suffix(self): ...
