# Stubs for django.db.backends.mysql.schema (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.base.schema import BaseDatabaseSchemaEditor

class DatabaseSchemaEditor(BaseDatabaseSchemaEditor):
    sql_rename_table = ...  # type: str
    sql_alter_column_null = ...  # type: str
    sql_alter_column_not_null = ...  # type: str
    sql_alter_column_type = ...  # type: str
    sql_rename_column = ...  # type: str
    sql_delete_unique = ...  # type: str
    sql_create_fk = ...  # type: str
    sql_delete_fk = ...  # type: str
    sql_delete_index = ...  # type: str
    alter_string_set_null = ...  # type: str
    alter_string_drop_null = ...  # type: str
    sql_create_pk = ...  # type: str
    sql_delete_pk = ...  # type: str
    def quote_value(self, value): ...
    def skip_default(self, field): ...
    def add_field(self, model, field): ...
