# Stubs for django.db.backends.mysql.validation (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.base.validation import BaseDatabaseValidation

class DatabaseValidation(BaseDatabaseValidation):
    def check_field(self, field, **kwargs): ...
