# Stubs for django.conf.locale.te.formats (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

DATE_FORMAT = ...  # type: str
TIME_FORMAT = ...  # type: str
MONTH_DAY_FORMAT = ...  # type: str
SHORT_DATE_FORMAT = ...  # type: str
