# Stubs for django.contrib.messages.constants (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

DEBUG = ...  # type: int
INFO = ...  # type: int
SUCCESS = ...  # type: int
WARNING = ...  # type: int
ERROR = ...  # type: int
DEFAULT_TAGS = ...  # type: Any
DEFAULT_LEVELS = ...  # type: Any
