# Stubs for django.contrib.messages.middleware (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class MessageMiddleware:
    def process_request(self, request): ...
    def process_response(self, request, response): ...
