# Stubs for django.contrib.messages.views (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class SuccessMessageMixin:
    success_message = ...  # type: str
    def form_valid(self, form): ...
    def get_success_message(self, cleaned_data): ...
