# Stubs for django.contrib.gis.db.backends.spatialite.introspection (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.db.backends.sqlite3.introspection import DatabaseIntrospection, FlexibleFieldLookupDict

class GeoFlexibleFieldLookupDict(FlexibleFieldLookupDict):
    base_data_types_reverse = ...  # type: Any

class SpatiaLiteIntrospection(DatabaseIntrospection):
    data_types_reverse = ...  # type: Any
    def get_geometry_type(self, table_name, geo_col): ...
    def get_indexes(self, cursor, table_name): ...
