# Stubs for django.core.checks.compatibility.django_1_8_0 (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def check_duplicate_template_settings(app_configs, **kwargs): ...
