# Stubs for django.core.checks.messages (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

DEBUG = ...  # type: int
INFO = ...  # type: int
WARNING = ...  # type: int
ERROR = ...  # type: int
CRITICAL = ...  # type: int

class CheckMessage:
    level = ...  # type: Any
    msg = ...  # type: Any
    hint = ...  # type: Any
    obj = ...  # type: Any
    id = ...  # type: Any
    def __init__(self, level, msg, hint: Optional[Any] = ..., obj: Optional[Any] = ..., id: Optional[Any] = ...) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def is_serious(self): ...
    def is_silenced(self): ...

class Debug(CheckMessage):
    def __init__(self, *args, **kwargs) -> None: ...

class Info(CheckMessage):
    def __init__(self, *args, **kwargs) -> None: ...

class Warning(CheckMessage):
    def __init__(self, *args, **kwargs) -> None: ...

class Error(CheckMessage):
    def __init__(self, *args, **kwargs) -> None: ...

class Critical(CheckMessage):
    def __init__(self, *args, **kwargs) -> None: ...
