# Stubs for django.core.checks.model_checks (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def check_all_models(app_configs: Optional[Any] = ..., **kwargs): ...
def check_model_signals(app_configs: Optional[Any] = ..., **kwargs): ...
