# Stubs for django.db.backends.dummy.base (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.db.backends.base.base import BaseDatabaseWrapper
from django.db.backends.base.client import BaseDatabaseClient
from django.db.backends.base.creation import BaseDatabaseCreation
from django.db.backends.base.introspection import BaseDatabaseIntrospection
from django.db.backends.base.operations import BaseDatabaseOperations

def complain(*args, **kwargs): ...
def ignore(*args, **kwargs): ...

class DatabaseError(Exception): ...
class IntegrityError(DatabaseError): ...

class DatabaseOperations(BaseDatabaseOperations):
    quote_name = ...  # type: Any

class DatabaseClient(BaseDatabaseClient):
    runshell = ...  # type: Any

class DatabaseCreation(BaseDatabaseCreation):
    create_test_db = ...  # type: Any
    destroy_test_db = ...  # type: Any

class DatabaseIntrospection(BaseDatabaseIntrospection):
    get_table_list = ...  # type: Any
    get_table_description = ...  # type: Any
    get_relations = ...  # type: Any
    get_indexes = ...  # type: Any
    get_key_columns = ...  # type: Any

class DatabaseWrapper(BaseDatabaseWrapper):
    operators = ...  # type: Any
    ensure_connection = ...  # type: Any
    features = ...  # type: Any
    ops = ...  # type: Any
    client = ...  # type: Any
    creation = ...  # type: Any
    introspection = ...  # type: Any
    validation = ...  # type: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def is_usable(self): ...
