# Stubs for django.db.backends.dummy.features (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.backends.base.features import BaseDatabaseFeatures

class DummyDatabaseFeatures(BaseDatabaseFeatures):
    supports_transactions = ...  # type: bool
