# Stubs for django.core.cache.utils (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

TEMPLATE_FRAGMENT_KEY_TEMPLATE = ...  # type: str

def make_template_fragment_key(fragment_name, vary_on: Optional[Any] = ...): ...
