# Stubs for django.db.backends.oracle.functions (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.db.models import Func

class IntervalToSeconds(Func):
    function = ...  # type: str
    template = ...  # type: str
    def __init__(self, expression, **extra) -> None: ...

class SecondsToInterval(Func):
    function = ...  # type: str
    template = ...  # type: str
    def __init__(self, expression, **extra) -> None: ...
