# Stubs for django.contrib.staticfiles.testing (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.test import LiveServerTestCase

class StaticLiveServerTestCase(LiveServerTestCase):
    static_handler = ...  # type: Any
