# Stubs for django.contrib.gis.forms (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.forms import *
from .fields import GeometryCollectionField as GeometryCollectionField, GeometryField as GeometryField, LineStringField as LineStringField, MultiLineStringField as MultiLineStringField, MultiPointField as MultiPointField, MultiPolygonField as MultiPolygonField, PointField as PointField, PolygonField as PolygonField
from .widgets import BaseGeometryWidget as BaseGeometryWidget, OpenLayersWidget as OpenLayersWidget, OSMWidget as OSMWidget
