# Stubs for django.contrib.gis.forms.widgets (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.forms.widgets import Widget

logger = ...  # type: Any

class BaseGeometryWidget(Widget):
    geom_type = ...  # type: str
    map_srid = ...  # type: int
    map_width = ...  # type: int
    map_height = ...  # type: int
    display_raw = ...  # type: bool
    supports_3d = ...  # type: bool
    template_name = ...  # type: str
    attrs = ...  # type: Any
    def __init__(self, attrs: Optional[Any] = ...) -> None: ...
    def serialize(self, value): ...
    def deserialize(self, value): ...
    def render(self, name, value, attrs: Optional[Any] = ...): ...

class OpenLayersWidget(BaseGeometryWidget):
    template_name = ...  # type: str
    class Media:
        js = ...  # type: Any

class OSMWidget(BaseGeometryWidget):
    template_name = ...  # type: str
    default_lon = ...  # type: int
    default_lat = ...  # type: int
    class Media:
        js = ...  # type: Any
    def __init__(self, attrs: Optional[Any] = ...) -> None: ...
    @property
    def map_srid(self): ...
