# Stubs for django.contrib.gis.views (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional
from django.utils.translation import ugettext as _

def feed(request, url, feed_dict: Optional[Any] = ...): ...
