# Stubs for django.contrib.staticfiles.management.commands.findstatic (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.core.management.base import LabelCommand

class Command(LabelCommand):
    help = ...  # type: str
    label = ...  # type: str
    def add_arguments(self, parser): ...
    def handle_label(self, path, **options): ...
