# Stubs for django.contrib.gis.db.backends.postgis.const (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

GDAL_TO_POSTGIS = ...  # type: Any
POSTGIS_TO_GDAL = ...  # type: Any
POSTGIS_HEADER_STRUCTURE = ...  # type: str
GDAL_TO_STRUCT = ...  # type: Any
STRUCT_SIZE = ...  # type: Any
