# Stubs for django.contrib.gis.db.backends.postgis.introspection (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.db.backends.postgresql.introspection import DatabaseIntrospection

class GeoIntrospectionError(Exception): ...

class PostGISIntrospection(DatabaseIntrospection):
    postgis_types_reverse = ...  # type: Any
    ignored_tables = ...  # type: Any
    def get_postgis_types(self): ...
    def get_field_type(self, data_type, description): ...
    def get_geometry_type(self, table_name, geo_col): ...
