# Stubs for django.contrib.admindocs.middleware (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class XViewMiddleware:
    def process_view(self, request, view_func, view_args, view_kwargs): ...
