# Stubs for django.db.backends.sqlite3.features (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from django.db.backends.base.features import BaseDatabaseFeatures
from .base import Database as Database

pytz = ...  # type: Any

class DatabaseFeatures(BaseDatabaseFeatures):
    can_use_chunked_reads = ...  # type: bool
    test_db_allows_multiple_connections = ...  # type: bool
    supports_unspecified_pk = ...  # type: bool
    supports_timezones = ...  # type: bool
    supports_1000_query_parameters = ...  # type: bool
    supports_mixed_date_datetime_comparisons = ...  # type: bool
    has_bulk_insert = ...  # type: bool
    can_combine_inserts_with_and_without_auto_increment_pk = ...  # type: bool
    supports_foreign_keys = ...  # type: bool
    supports_column_check_constraints = ...  # type: bool
    autocommits_when_autocommit_is_off = ...  # type: bool
    can_introspect_decimal_field = ...  # type: bool
    can_introspect_positive_integer_field = ...  # type: bool
    can_introspect_small_integer_field = ...  # type: bool
    supports_transactions = ...  # type: bool
    atomic_transactions = ...  # type: bool
    can_rollback_ddl = ...  # type: bool
    supports_paramstyle_pyformat = ...  # type: bool
    supports_sequence_reset = ...  # type: bool
    can_clone_databases = ...  # type: bool
    def uses_savepoints(self): ...
    def can_release_savepoints(self): ...
    def can_share_in_memory_db(self): ...
    def supports_stddev(self): ...
    def has_zoneinfo_database(self): ...
