# Stubs for django.contrib.flatpages.sitemaps (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.apps import apps as django_apps
from django.contrib.sitemaps import Sitemap

class FlatPageSitemap(Sitemap):
    def items(self): ...
